version: '3.8'

services:
  clash-test:
    build: .
    container_name: clash-test-env
    hostname: clash-test
    # 保持容器运行
    stdin_open: true
    tty: true
    # 端口映射
    ports:
      - "7890:7890"   # HTTP 代理
      - "7891:7891"   # SOCKS5 代理
      - "9090:9090"   # API 端口
    # 挂载卷，映射本地目录到容器家目录
    volumes:
      - .:/home/testuser
      - clash-config:/home/testuser/.config/mihomo
    # 网络配置
    networks:
      - clash-net
    # 资源限制（可选）
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

# 自定义网络
networks:
  clash-net:
    driver: bridge

# 持久化卷
volumes:
  clash-config: